server:
  port: 8081
spring:
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - com.azure.spring.cloud.autoconfigure.implementation.data.cosmos.CosmosDataAutoConfiguration
      - com.azure.spring.cloud.autoconfigure.implementation.cosmos.AzureCosmosAutoConfiguration
      - com.azure.spring.cloud.autoconfigure.implementation.data.cosmos.CosmosRepositoriesAutoConfiguration
  datasource:
    url: jdbc:sqlserver://azsqltest03s.database.windows.net;databaseName=azsqltest03;encrypt=false;trustServerCertificate=false;DB_CLOSE_DELAY=-1
    username: adrian
    password: ${SQLSERVER_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  liquibase:
    change-log: classpath:db/changelog/database.yaml
    enabled: true
  data:
    mongodb:
      # Sin autenticación (local)
      uri: mongodb://localhost:27017/credit_card_db
      # Con autenticación (descomentar y quitar uri de arriba)
      host: localhost
      port: 27017
      database: credit_card_db
      username: your_user
      password: your_password
api:
  convert:
    url: http://localhost:3001/convert/currency/